#!/usr/bin/with-contenv bash

export PAPERLESS_REDIS=${REDIS_URL:-redis://localhost:6379}

cd /app/paperless/src || exit

# remove services unless they're enabled
if [[ -z "$REDIS_URL" ]]; then
    echo "Waiting for redis to become available..."
    sleep 10
fi

exec \
    s6-setuidgid abc /usr/local/bin/gunicorn -c /app/paperless/gunicorn.conf.py paperless.asgi:application
