#!/usr/bin/with-contenv bash

export PAPERLESS_REDIS=${REDIS_URL:-redis://localhost:6379}

cd /app/paperless/src || exit

# remove services unless they're enabled
if [[ -z "$REDIS_URL" ]]; then
    echo "Waiting for redis to become available..."
    sleep 10
fi

exec \
    s6-setuidgid abc python3 manage.py document_consumer
